### ISSUE TITLE
CHANGELOG Documents a Parameter Rename as a Bug Fix

### ISSUE THREAD

**Issue by AnisGLZ** [nicovandenhooff/reddit-data-collector#17]
Affected File: CHANGELOG.md

The CHANGELOG entry for v1.0.1 reads:

    "Spelling error of separate argument in to_pandas function of
     reddit_data_collector.io.py, previously it was spelt like seperate"

Renaming a parameter from `seperate` to `separate` is a breaking change for any caller who used the misspelled keyword argument by name: `to_pandas(seperate=True)` on v1.0.0 would raise a TypeError ("unexpected keyword argument 'seperate'") after upgrading to v1.0.1 without any deprecation warning period.

The CHANGELOG entry categorises this as a bug fix without flagging it as a potentially breaking API change, and does not include a migration note.

Any user of v1.0.0 who called the function with the misspelled keyword argument by name would encounter a silent breakage on upgrade. The CHANGELOG does not clearly distinguish breaking changes from bug fixes.

Adopt a structured CHANGELOG format (e.g., Keep a Changelog) that distinguishes Added, Changed, Deprecated, Removed, Fixed, and Security sections. Mark any parameter or function renames as "Changed" with a note that they may break existing call sites. For future releases, use a deprecation warning (warnings.warn with DeprecationWarning) for renamed or removed parameters for at least one release cycle before removal.
